title: Do Something Amateur Radio Club
email: contact@dsarc.us
description: >
 DSARC is based out of Moscow, in Latah County Idaho. The club was founded for those hams who actually want to get out and do activities. While we are primarily an amateur radio club, we also focus on emergency communications, preparedness, and response. DSARC is also proud to support the Latah County Aux Comm Team in it's training efforts. DSARC is also proudly supported by Northwest Radio Supply.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dsarc.us" # the base hostname & protocol for your site, e.g. http://example.com

# Social
facebook_username: dosomethingarc
twitter_username: dosomethingarc

# Public Repositories
gitlab_username:  dsarc

# Comments
disqus:
  shortname: dsarc

# Where things are.
include:
  - _pages

# Collections
collections:
  classes:
    output: true
    permalink: /:collection/:path/
  minutes:
    output: true
    permalink: /:collection/:path/

# Site settings
paginate: 5

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
